### ISSUE TITLE
Way to run energyrunner automatically

### ISSUE THREAD

**Issue by BeyondCloud** [eembc/energyrunner#19]
Hi, is there any way to control the energyrunner via command line interface? I need to make the benchmark process run automatically.

**Comment by petertorelli** [comment]
There is a beta interface that is not documented as it isn't complete yet. Here is how you would launch MLPerf Tiny:

Create a file called `script.sync` like this. This script will initialize the benchmark for Performance Mode, set the inference iterations to 1500, and run the benchmark:

```
bm init ulp-mlperf
bm cfg ulp-mlperf iterInfer 1500
bm run ulp-mlperf
```

Use the code `ulp-mlperf` for the Performance Mode of the benchmark, and `ulp-ml` for Energy Mode.

To run the script, invoke the framework as follows:

Windows (command prompt, not PowerShell):

```
C:\>start /B /WAIT "RUNNER" ".\EEMBC Host Benchmark Framework.exe" --script=script.sync
```

macOS (from the *.app directory):

```
% ./EEMBC\ Host\ Benchmark\ Framework --script=script.sync
```

Linux:

```
$ ./benchmark-framework --script=script.sync
```

**Comment by BeyondCloud** [comment]
I'm a Mac user and I created a script script.sync you mentioned above in the directory `/Applications/EEMBC Host Benchmark Framework.app/Contents/MacOS`
When I ran the command 
```
./EEMBC\ Host\ Benchmark\ Framework --script=script.sync
```
I got the following error:
```
...
00002.145 parser: Command "run /Applications/EEMBC Host Benchmark Framework.app/Contents/MacOS/script.sync"
Error: Script must be .sync or .async
    at Object.fn (/Applications/EEMBC Host Benchmark Framework.app/Contents/Resources/app.asar/webpack:/src/framework/parser.ts:621:19)
    at parser_parse (/Applications/EEMBC Host Benchmark Framework.app/Contents/Resources/app.asar/webpack:/src/framework/parser.ts:666:34)
    at process.sendToParser (/Applications/EEMBC Host Benchmark Framework.app/Contents/Resources/app.asar/webpack:/src/framework/worker-thread.ts:56:5)
    at process.emit (events.js:310:20)
    at process.emit (/Applications/EEMBC Host Benchmark Framework.app/Contents/Resources/app.asar/node_modules/source-map-support/source-map-support.js:495:21)
    at emit (internal/child_process.js:876:12)
    at processTicksAndRejections (internal/process/task_queues.js:85:21)
00002.212 parser: e-[Command 'run' failed: Script must be .sync or .async]
```
I handle this error by renaming `/Applications/EEMBC Host Benchmark Framework.app` to other name without space such as `/Applications/EEMBC.app` .

**Comment by petertorelli** [comment]
You are correct, this is a bug. This will be fixed in the next release. Thank you for filing.

**Comment by BeyondCloud** [comment]
Hi, I could measure the throughput of single data now.
Could you tell me how to measure the accuracy and medium performance by editing script.sync? 
Thanks

**Comment by BeyondCloud** [comment]
Solved:
medium performance
```
bm init ulp-mlperf
bm cfg ulp-mlperf runMode bmark
bm run ulp-mlperf
```
accuracy
```
bm init ulp-mlperf
bm cfg ulp-mlperf runMode multi
bm run ulp-mlperf
```

**Comment by petertorelli** [comment]
Nice! You probably observed that all of the GUI buttons do nothing more than send commands to the parser--like the ones you have listed above--and are visible from the console.
