### ISSUE TITLE
Missing download links for the EEMBC Benchmark Framework.exe Tool and the IO manager image

### ISSUE THREAD

**Issue by nessriines** [eembc/energyrunner#28]
Hi All,

I am unable to find links download the EEMBC Benchmark Framework.exe Tool and the IO manager image.

Can you please provide links that directly allow me to download the above mentioned Tool and Image.
Thank you!
Nissrine

**Comment by petertorelli** [comment]
What happens when you follow the link in the README?

**Comment by nessriines** [comment]
there is no link in the README :/

**Comment by petertorelli** [comment]
https://github.com/eembc/energyrunner#runner-binaries

**Comment by nessriines** [comment]
Thank you so much @petertorelli for your help :)
So, I will close this issue.
Best regards

**Comment by nessriines** [comment]
Hi @petertorelli 
Could you please provide me link to download the iotconnect.exe ?
Thank you
