### ISSUE TITLE
Reference port on L4R5ZI hangs after ~1000 images on ad01

### ISSUE THREAD

**Issue by petertorelli** [eembc/energyrunner#3]
There is a known sighting where the reference port stops working after about 1000-2000 inferences when running validation for the anomaly detection NN on macOS. This appears to be related to USB dropping, but it has not been root caused. The problem does not occur on Windows 10 or Linux (Ubuntu 18.04).

**Comment by BeyondCloud** [comment]
I encountered the same issue when uploading binary image of ic01 to Numaker-IOT-M487. The command "db upload  xxx" stuck randomly and I could never run the whole accuracy measurement process. Again, this problem doesn't happen on Windows 10 or Linux.

**Comment by petertorelli** [comment]
The solution is to upgrade the STLink firmware to version `V2J37M27` using their CubeMX Programmer software.
